---
- name: resolver
  recipe: internal-service
  clients: workflow
  image: quay.io/ukhomeofficedigital/asl-resolver:{{.DRONE_COMMIT_SHA}}
  env:
    DATABASE_HOST:
      secret: true
      name: asl-dev-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asl-dev-rds
      key: db_name
    DATABASE_USERNAME:
      secret: true
      name: asl-dev-rds
      key: username
    DATABASE_PASSWORD:
      secret: true
      name: asl-dev-rds
      key: password
    DATABASE_PORT:
      secret: true
      name: asl-dev-rds
      key: port
