---
- name: resolver
  recipe: worker
  image: quay.io/ukhomeofficedigital/asl-resolver:{{.DRONE_COMMIT_SHA}}
  env:
    DATABASE_HOST:
      secret: true
      name: asl-dev-rds
      key: endpoint
    DATABASE_NAME:
      secret: true
      name: asl-dev-rds
      key: db_name
    DATABASE_USERNAME:
      secret: true
      name: asl-dev-rds
      key: username
    DATABASE_PASSWORD:
      secret: true
      name: asl-dev-rds
      key: password
    DATABASE_PORT:
      secret: true
      name: asl-dev-rds
      key: port
    SQS_REGION: eu-west-2
    SQS_ACCESS_KEY:
      secret: true
      name: asl-changerequests-dev-sqs
      key: access_key_id
    SQS_SECRET:
      secret: true
      name: asl-changerequests-dev-sqs
      key: secret_access_key
    SQS_URL:
      secret: true
      name: asl-changerequests-dev-sqs
      key: sqs_queue_url
    JWT_SECRET:
      secret: true
      name: asl-dev-jwt
      key: token
    KEYCLOAK_REALM: Asl-dev
    KEYCLOAK_URL: https://sso-dev.notprod.homeoffice.gov.uk/auth
    KEYCLOAK_CLIENT: asl-dev-connect
    KEYCLOAK_SECRET:
      secret: true
      name: asl-dev-auth
      key: secret
    KEYCLOAK_USERNAME:
      secret: true
      name: asl-dev-keycloak
      key: username
    KEYCLOAK_PASSWORD:
      secret: true
      name: asl-dev-keycloak
      key: password
    EMAILER_SERVICE: https://emailer:10443
